// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeiRmtqaZpsSu0pJRAIqWDK4HdwZfYsK4',
    appId: '1:527466144398:web:21f31aba8490e0e1611fdf',
    messagingSenderId: '527466144398',
    projectId: 'fashion-ecommerce-app-b0607',
    authDomain: 'fashion-ecommerce-app-b0607.firebaseapp.com',
    storageBucket: 'fashion-ecommerce-app-b0607.firebasestorage.app',
    measurementId: 'G-6M01Q3EJDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlxv3QwkrkWWc86uMrwVB-ZYIEhC4bdl8',
    appId: '1:527466144398:android:10ce7d281c47d4eb611fdf',
    messagingSenderId: '527466144398',
    projectId: 'fashion-ecommerce-app-b0607',
    storageBucket: 'fashion-ecommerce-app-b0607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpQjcf_kGa4SgPOogdR4vJkeVUay28p1I',
    appId: '1:527466144398:ios:6910836645d8caaa611fdf',
    messagingSenderId: '527466144398',
    projectId: 'fashion-ecommerce-app-b0607',
    storageBucket: 'fashion-ecommerce-app-b0607.firebasestorage.app',
    iosBundleId: 'com.example.fashionEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpQjcf_kGa4SgPOogdR4vJkeVUay28p1I',
    appId: '1:527466144398:ios:6910836645d8caaa611fdf',
    messagingSenderId: '527466144398',
    projectId: 'fashion-ecommerce-app-b0607',
    storageBucket: 'fashion-ecommerce-app-b0607.firebasestorage.app',
    iosBundleId: 'com.example.fashionEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeiRmtqaZpsSu0pJRAIqWDK4HdwZfYsK4',
    appId: '1:527466144398:web:a81b5b572e34f823611fdf',
    messagingSenderId: '527466144398',
    projectId: 'fashion-ecommerce-app-b0607',
    authDomain: 'fashion-ecommerce-app-b0607.firebaseapp.com',
    storageBucket: 'fashion-ecommerce-app-b0607.firebasestorage.app',
    measurementId: 'G-FM3MN954SE',
  );
}
